---------------------- JOIN 종합 실습문제 ----------------------
-- 1. 직급이 대리이면서 ASIA 지역에 근무하는 직원들의
--    사번, 사원명, 직급명, 부서명, 근무지역명, 급여를 조회하시오
-->> 오라클 전용 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.LOCAL_NAME, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D, JOB J, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND E.JOB_CODE = J.JOB_CODE(+)
AND D.LOCATION_ID = L.LOCAL_CODE(+)
AND J.JOB_NAME = '대리'
AND L.LOCAL_NAME LIKE 'ASIA%';
-->> ANSI 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.LOCAL_NAME, E.SALARY
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
LEFT JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
WHERE J.JOB_NAME = '대리'
AND L.LOCAL_NAME LIKE 'ASIA%';


-- 2. 70년대생이면서 여자이고, 성이 정씨인 직원들의
--   사원명, 주민번호, 부서명, 직급명을 조회하시오
-->> 오라클 전용 구문
SELECT E.EMP_NAME, E.EMP_NO, D.DEPT_TITLE, J.JOB_NAME
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND E.JOB_CODE = J.JOB_CODE(+)
AND SUBSTR(E.EMP_NO, 1, 1) = '7'
AND SUBSTR(E.EMP_NO, 8, 1) = '2'
AND E.EMP_NAME LIKE '정%';
-->> ANSI 구문
SELECT E.EMP_NAME, E.EMP_NO, D.DEPT_TITLE, J.JOB_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE SUBSTR(E.EMP_NO, 1, 1) = '7'
AND SUBSTR(E.EMP_NO, 8, 1) = '2'
AND E.EMP_NAME LIKE '정%';


-- 3. 이름에 '영'자가 들어있는 직원들의 
--    사번, 사원명, 직급명을 조회하시오
-->> 오라클 전용 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE(+)
AND E.EMP_NAME LIKE '%영%';
-->> ANSI 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME
FROM EMPLOYEE E
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE E.EMP_NAME LIKE '%영%';


-- 4. 해외영업팀에 근무하는 직원들의
--    사원명, 직급명, 부서코드, 부서명을 조회하시오
-->> 오라클 전용 구문
SELECT E.EMP_NAME, J.JOB_NAME, D.DEPT_ID, D.DEPT_TITLE
FROM EMPLOYEE E, JOB J, DEPARTMENT D
WHERE E.JOB_CODE = J.JOB_CODE(+)
AND E.DEPT_CODE = D.DEPT_ID(+)
AND D.DEPT_TITLE LIKE '해외영업%';
-->> ANSI 구문
SELECT E.EMP_NAME, J.JOB_NAME, D.DEPT_ID, D.DEPT_TITLE
FROM EMPLOYEE E
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
WHERE D.DEPT_TITLE LIKE '해외영업%';


-- 5. 보너스를 받는 직원들의
--    사원명, 보너스, 연봉, 부서명, 근무지역명을 조회하시오
-->> 오라클 전용 구문
SELECT E.EMP_NAME, E.BONUS, E.SALARY * 12 AS 연봉, D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND D.LOCATION_ID = L.LOCAL_CODE(+)
AND E.BONUS IS NOT NULL;
-->> ANSI 구문
SELECT E.EMP_NAME, E.BONUS, E.SALARY * 12 AS 연봉, D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
LEFT JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
WHERE E.BONUS IS NOT NULL;


-- 6. 부서가 있는 직원들의
--    사원명, 직급명, 부서명, 근무지역명을 조회하시오
-->> 오라클 전용 구문
SELECT E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L
WHERE E.JOB_CODE = J.JOB_CODE(+)
AND E.DEPT_CODE = D.DEPT_ID(+)
AND D.LOCATION_ID = L.LOCAL_CODE(+)
AND E.DEPT_CODE IS NOT NULL;
-->> ANSI 구문
SELECT E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
LEFT JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
WHERE E.DEPT_CODE IS NOT NULL;


-- 7. '한국' 과 '일본' 에 근무하는 직원들의
--    사원명, 부서명, 근무지역명, 근무국가명을 조회하시오
--    단, 이름 기준 가나다순으로 정렬해서 조회
-->> 오라클 전용 구문
SELECT E.EMP_NAME, D.DEPT_TITLE, L.LOCAL_NAME, N.NATIONAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, NATIONAL N
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND D.LOCATION_ID = L.LOCAL_CODE(+)
AND L.NATIONAL_CODE = N.NATIONAL_CODE(+)
AND N.NATIONAL_NAME IN ('한국', '일본');
-->> ANSI 구문
SELECT E.EMP_NAME, D.DEPT_TITLE, L.LOCAL_NAME, N.NATIONAL_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
LEFT JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
LEFT JOIN NATIONAL N ON L.NATIONAL_CODE = N.NATIONAL_CODE
WHERE N.NATIONAL_NAME IN ('한국', '일본');


-- 8. 보너스를 받지 않는 직원들 중 직급코드가 J4 또는 J7 인 직원들의
--    사원명, 직급명, 급여를 조회하시오
-->> 오라클 전용 구문
SELECT E.EMP_NAME, J.JOB_NAME, E.SALARY
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE(+)
AND E.BONUS IS NULL
AND E.JOB_CODE IN ('J4', 'J7');
-->> ANSI 구문
SELECT E.EMP_NAME, J.JOB_NAME, E.SALARY
FROM EMPLOYEE E
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE E.BONUS IS NULL
AND E.JOB_CODE IN ('J4', 'J7');


-- 9. 사번, 사원명, 직급명, 급여등급, 구분을 조회하는데
--    이 때, 구분에 해당하는 값은
--    급여등급이 S1, S2 인 경우 '고급'
--    급여등급이 S3, S4 인 경우 '중급'
--    급여등급이 S5, S6 인 경우 '초급' 으로 조회되게 하시오
-->> 오라클 전용 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, S.SAL_LEVEL,
    CASE
        WHEN S.SAL_LEVEL IN ('S1', 'S2') THEN '고급'
        WHEN S.SAL_LEVEL IN ('S3', 'S4') THEN '중급'
        WHEN S.SAL_LEVEL IN ('S5', 'S6') THEN '초급'
        ELSE '미정'
    END AS 구분
FROM EMPLOYEE E, JOB J, SAL_GRADE S
WHERE E.JOB_CODE = J.JOB_CODE(+)
AND E.SAL_LEVEL = S.SAL_LEVEL(+);
-->> ANSI 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, S.SAL_LEVEL,
    CASE
        WHEN S.SAL_LEVEL IN ('S1', 'S2') THEN '고급'
        WHEN S.SAL_LEVEL IN ('S3', 'S4') THEN '중급'
        WHEN S.SAL_LEVEL IN ('S5', 'S6') THEN '초급'
        ELSE '미정'
    END AS 구분
FROM EMPLOYEE E
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
LEFT JOIN SAL_GRADE S ON E.SAL_LEVEL = S.SAL_LEVEL;


-- 10. 각 부서별 총 급여합을 조회하되
--     이 때, 총 급여합이 1000만원 이상인 부서명, 급여합을 조회하시오
-->> 오라클 전용 구문
SELECT D.DEPT_TITLE, SUM(E.SALARY) AS 총급여합
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID(+)
GROUP BY D.DEPT_TITLE
HAVING SUM(E.SALARY) >= 10000000;
-->> ANSI 구문
SELECT D.DEPT_TITLE, SUM(E.SALARY) AS 총급여합
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
GROUP BY D.DEPT_TITLE
HAVING SUM(E.SALARY) >= 10000000;


-- 11. 각 부서별 평균급여를 조회하여 부서명, 평균급여 (정수처리) 로 조회하시오
--     단, 부서배치가 안된 사원들의 평균도 같이 나오게끔 하시오
-->> 오라클 전용 구문
SELECT D.DEPT_TITLE, FLOOR(AVG(E.SALARY)) AS 평균급여
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID(+)
GROUP BY D.DEPT_TITLE;
-->> ANSI 구문
SELECT D.DEPT_TITLE, FLOOR(AVG(E.SALARY)) AS 평균급여
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
GROUP BY D.DEPT_TITLE;

-- 12. 2010년 이후 입사한 '이'씨 성을 가진 사원의 사원 코드, 사원 명, 부서명 조회
-->> 오라클 전용 구문
SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND EXTRACT(YEAR FROM E.HIRE_DATE) > 2010
AND E.EMP_NAME LIKE '이%';
-->> ANSI 구문
SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_TITLE
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
WHERE EXTRACT(YEAR FROM E.HIRE_DATE) > 2010
AND E.EMP_NAME LIKE '이%';


-- 13. 부서 코드가 D5이거나 D6인 사원의 사원 명, 직급코드, 부서 코드, 부서 명 조회
-->> 오라클 전용 구문
SELECT E.EMP_NAME, E.JOB_CODE, E.DEPT_CODE, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND E.DEPT_CODE IN ('D5', 'D6');
-->> ANSI 구문
SELECT E.EMP_NAME, E.JOB_CODE, E.DEPT_CODE, D.DEPT_TITLE
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
WHERE E.DEPT_CODE IN ('D5', 'D6');


-- 14. 직급이 '과장' 인 사원들의 사번, 사원 명, 직급 명, 급여, 입사일 조회
-->> 오라클 전용 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, E.SALARY, E.HIRE_DATE
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE(+)
AND J.JOB_NAME = '과장';
-->> ANSI 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, E.SALARY, E.HIRE_DATE
FROM EMPLOYEE E
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE J.JOB_NAME = '과장';


-- 15. 70년대 생(1970~1979) 인 사원의 이름과, 주민번호, 부서명 조회
-->> 오라클 전용 구문
SELECT E.EMP_NAME, E.EMP_NO, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND SUBSTR(E.EMP_NO, 1, 1) = '7';
-->> ANSI 구문
SELECT E.EMP_NAME, E.EMP_NO, D.DEPT_TITLE
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
WHERE SUBSTR(E.EMP_NO, 1, 1) = '7';


-- 16. 부서 배치가 되지 않은 사원들의 사원명, 급여, 부서명 ("미정") 으로 조회
-->> 오라클 전용 구문
SELECT EMP_NAME, SALARY, NVL(DEPT_TITLE, '미정') AS DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND E.DEPT_CODE IS NULL;
-->> ANSI 구문
SELECT E.EMP_NAME, E.SALARY, NVL(D.DEPT_TITLE, '미정') AS DEPT_TITLE
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
WHERE E.DEPT_CODE IS NULL;


-- 17. 성별이 남자인 사원들의 사번, 사원 명, 부서 명, 직급 명, 급여, 입사일 조회
-->> 오라클 전용 구문
SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_TITLE, J.JOB_NAME, E.SALARY, E.HIRE_DATE
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND E.JOB_CODE = J.JOB_CODE(+)
AND SUBSTR(E.EMP_NO, 8 ,1) IN ('1', '3');
-->> ANSI 구문
SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_TITLE, J.JOB_NAME, E.SALARY, E.HIRE_DATE
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
LEFT JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE SUBSTR(E.EMP_NO, 8 ,1) IN ('1', '3');

